#!/usr/bin/env python

import os
from subprocess import Popen
from subprocess import PIPE
from subprocess import STDOUT

def run_cmd(cmd):

    print("Executing {}".format(cmd))

    process = Popen(cmd,
                    shell=True,
                    bufsize=0,
                    stdout=PIPE,
                    stderr=STDOUT)

    line = process.stdout.readline()

    while line:
        line = line.strip()
        print(line)
        line = process.stdout.readline()

    out,error = process.communicate()
    exitcode = process.returncode

    if exitcode != 0: 
        print('FAILED: executing cmd "{}" failed'.format(cmd))
        print("exitcode {}".format(exitcode))

    return exitcode

docker_build_dir = os.environ.get("DOCKER_BUILD_DIR")

if not docker_build_dir: 
    docker_build_dir = "/var/tmp/docker/build"

scripts_dir = "/opt/config0/scripts"
_script = os.environ.get("DOCKER_CMD_SCRIPT")
dest_file_name = os.environ.get("DEST_FILENAME")

if not dest_file_name: 
    dest_file_name = "run.sh"

if not _script:
    print("No DOCKER_CMD_SCRIPT to execute")
    exit(0)

os.chdir(scripts_dir)

src_file = os.path.join(scripts_dir,_script)
dest_file = os.path.join(docker_build_dir,dest_file_name)

exitcode = run_cmd("cp -rp {} {}".format(src_file,dest_file))

if exitcode != 0: 
    exit(exitcode)
