#!/usr/bin/env python
#
import os
import sys
import string
import random

from subprocess import Popen
from subprocess import PIPE
from subprocess import STDOUT
from config0_publisher.shellouts import rm_rf

def run_cmd(cmd,exit_error=False):

    print('executing cmd "{}"'.format(cmd))

    exitcode = execute_return_exit(cmd)
    if exitcode == 0: return True

    if exit_error: exit(exitcode)

    return False

def run_cmds(cmds,exit_error=True):

    for cmd in cmds:
        print('Executing "{}"'.format(cmd))
        exitcode = execute_return_exit(cmd)
        if exitcode == 0: continue
        print('Executing "{}" failed with exitcode={}'.format(cmd,exitcode))
        if exit_error: sys.exit(1)
        return False

    return True

def execute(cmd,unbuffered=False):

    '''executes a shell command, returning status of execution,
    standard out, and standard error'''

    process = Popen(cmd,shell=True,bufsize=0,stdout=PIPE,stderr=STDOUT)

    line = process.stdout.readline()

    while line:
        line = line.strip()
        print(line)

    out,error = process.communicate()
    exitcode = process.returncode

    return exitcode
def id_generator(size=6,chars=string.ascii_uppercase+string.digits):

    '''generates id randomly'''

    return ''.join(random.choice(chars) for x in range(size))

def create_git_ssh_wrapper(filename="/tmp/git_ssh"):

    '''
    creates a temporary ssh wrapper script for using 
    ssh -i <private_key> to execute git 
    commands
    '''

    if os.path.exists(filename):
        print("ssh wrapper {} already exists".format(filename))
        return filename

    file_content = '''
#!/bin/bash

trap 'rm -f /tmp/.git_ssh.$$' 0

if [ "$1" = "-i" ]; then
    SSH_KEY=$2; shift; shift
    echo "GIT_TERMINAL_PROMPT=0 ssh -i $SSH_KEY -o StrictHostKeyChecking=no -oBatchMode=yes \$@" > /tmp/.git_ssh.$$
    chmod +x /tmp/.git_ssh.$$
    export GIT_SSH=/tmp/.git_ssh.$$
fi

[ "$1" = "git" ] && shift

# Run the git command
git "$@"
'''
    config_run = open(filename,'w')
    config_run.write(file_content)
    config_run.close()
    os.system("chmod 755 %s" % filename)

    return filename

def git_clone_repo(**kwargs):

    '''
    does a simple clone if repo doesn't exists 
    or does a pull if does exists
    '''

    repo_dir = kwargs["repo_dir"]
    git_url = kwargs.get("git_url")
    prv_key_loc = kwargs.get("prv_key_loc")
    commit = kwargs.get("commit")
    base_cmd = None

    branch = kwargs.get("branch")

    if not branch: 
        branch = "main"

    if prv_key_loc:
        wrapper_script = create_git_ssh_wrapper()
        base_cmd = "{} -i {}".format(wrapper_script,prv_key_loc)

    cmds = []

    ##################################################
    # No need to clone if the repo exists
    ##################################################
    cmd="cd {} && git status > /dev/null 2>&1".format(repo_dir)
    if os.path.exists(repo_dir) and int(execute_return_exit(cmd)) != 0: 
        print("directory {} exists, but it is not a git repo.  Deleting ...".format(repo_dir))
        rm_rf(repo_dir)

    if os.path.exists(repo_dir):

        #Get on a branch just in case - detached HEAD doesn't behave well
        cmd = "cd {} && git stash && git checkout {}".format(repo_dir,branch)
        run_cmd(cmd,exit_error=False)

        if commit: 
            add_cmd = "git pull"
        elif branch: 
            add_cmd = "git pull origin {}".format(branch)
        else:
            print("you need either a commit or branch to clone/update %s" % (repo_dir))
            return False

        if base_cmd: 
            cmds.append("cd {} && {} {}".format(repo_dir,base_cmd,add_cmd))
        else:
            cmds.append("cd {} && {}".format(repo_dir,add_cmd))

    else:

        if not git_url:
            print("git_url not given, not cloning %s" % (repo_dir))
            return False

        add_cmd = "git clone -b {} {} {}".format(branch,git_url,repo_dir)

        if base_cmd: 
            cmds.append("{} {}".format(base_cmd,add_cmd))
        else:
            cmds.append(add_cmd)
    
    if commit: 
        #Get on a branch just in case - detached HEAD doesn't behave well
        cmds.append("cd {} && git stash && git checkout {}".format(repo_dir,branch))

        add_cmd = "git checkout {}".format(commit)
        cmds.append("cd {} && {}".format(repo_dir,add_cmd))

    run_cmds(cmds)

    return True

def execute_return_exit(cmd):

    process = Popen(cmd,shell=True,bufsize=0,stdout=PIPE,stderr=STDOUT)

    line = process.stdout.readline()

    while line:
        line = line.strip()
        print(line)
        line = process.stdout.readline()

    out,error = process.communicate()
    exitcode = process.returncode

    return exitcode

if __name__ == '__main__':

    if len(sys.argv) != 3: 
        print("Need three arguments: prv_key_loc, git_url, repo_dir")
        exit(34)

    prv_key_loc = sys.argv[0]
    git_url = sys.argv[1]
    repo_dir = sys.argv[2]

    git_clone_repo(prv_key_loc=prv_key_loc,
                   git_url=git_url,
                   repo_dir=repo_dir)
