#!/usr/bin/env python

import os
from subprocess import Popen
from subprocess import PIPE
from subprocess import STDOUT

def run_cmd(cmd):

    print('executing cmd "{}"'.format(cmd))

    process = Popen(cmd,shell=True,bufsize=0,stdout=PIPE,stderr=STDOUT)

    line = process.stdout.readline()

    while line:
        line = line.strip()
        print(line)
        line = process.stdout.readline()

    out,error = process.communicate()
    exitcode = process.returncode

    if exitcode != 0: print('FAILED: executing cmd "{}" failed'.format(cmd))

    return exitcode

ufw_allows = os.environ.get("UFW_ALLOWS")
if not ufw_allows: exit(0)

for ufw_allow in ufw_allows:
    cmd = "ufw allow {}".format(ufw_allow.strip())
    run_cmd(cmd)

run_cmd("ufw status verbose")
