#!/usr/bin/env python

import os
import json
from config0_publisher.resource_manage import to_jsonfile
from config0_publisher.serialization import b64_encode

terraform_state_file = os.environ.get("TERRAFORM_STATE_FILE","terraform.tfstate")

with open(terraform_state_file) as json_file:
    data = json.load(json_file)

if not data:
    print("ERROR - there is no data from {}".format(os.path.join(os.getcwd(),terraform_state_file)))
    exit(9)

name = data["resources"][0]["name"]

results = {"name":name}
results["resource_type"] = "aws_instance"
results["provider"] = "aws"
results["main"] = True

# changed 45234532 - moved over to b64 hash
results["raw"] = {"terraform":b64_encode(data)}

for resource in data["resources"]:

    if resource["type"] != results["resource_type"]: continue

    results["_id"] = resource["instances"][0]["attributes"]["id"]
    results["ami"] = resource["instances"][0]["attributes"]["ami"]
    results["arn"] = resource["instances"][0]["attributes"]["arn"]
    
    results["private_dns"] = resource["instances"][0]["attributes"]["private_dns"]
    results["private_ip"] = resource["instances"][0]["attributes"]["private_ip"]
    
    if resource["instances"][0]["attributes"].get("public_dns"):
        results["public_dns"] = resource["instances"][0]["attributes"]["public_dns"]
    
    if resource["instances"][0]["attributes"].get("public_ip"):
        results["public_ip"] = resource["instances"][0]["attributes"]["public_ip"]
    
    results["tags"] = [ results["_id"], name ]

if os.environ.get("TF_VAR_aws_default_region"): 
    region = os.environ["TF_VAR_aws_default_region"]
elif os.environ.get("AWS_DEFAULT_REGION"): 
    region = os.environ["AWS_DEFAULT_REGION"]
else:
    region = None

if region:
    results["region"] = region
    results["aws_default_region"] = region

# ref 34532045732
to_jsonfile(results,"ec2_server.json")

