#!/bin/bash

export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:=""}
export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:=""}
export EKS_ROLENAME=${EKS_ROLENAME:=""}
export EKS_CLUSTER=${EKS_CLUSTER:=""}
export DOCKER_EXEC=${DOCKER_EXEC:=weaveworks/eksctl:0.82.0}
export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:=us-east-1}

export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query Account)

if [ "$AWS_ACCOUNT_ID" == "" ] ; then
    echo "AWS_ACCOUNT_ID needs to be set in environmental variable"
    exit 4
fi

if [ "$AWS_SECRET_ACCESS_KEY" == "" ] ; then
    echo "AWS_SECRET_ACCESS_KEY needs to be set in environmental variable"
    exit 4
fi

if [ "$AWS_ACCESS_KEY_ID" == "" ] ; then
    echo "AWS_ACCESS_KEY_ID needs to be set in environmental variable"
    exit 4
fi

if [ "$EKS_ROLENAME" == "" ] ; then
    echo "EKS_ROLENAME needs to be set in environmental variable"
    exit 4
fi

if [ "$EKS_CLUSTER" == "" ] ; then
    echo "EKS_CLUSTER needs to be set in environmental variable"
    exit 4
fi

export EKS_ROLEARN=arn:aws:iam::${AWS_ACCOUNT_ID}:role/${EKS_ROLENAME}
export EKSCTL_CMD_HASH=`echo "create iamidentitymapping --cluster $EKS_CLUSTER --arn ${EKS_ROLEARN} --group system:masters --username admin" | base64 -w 0`

docker run --rm -i \
-e AWS_ACCOUNT_ID \
-e AWS_ACCESS_KEY_ID \
-e AWS_SECRET_ACCESS_KEY \
-e AWS_DEFAULT_REGION \
$DOCKER_EXEC \
`echo $EKSCTL_CMD_HASH | base64 -d` || exit 9
