#!/usr/bin/env python

import os
import json
from config0_publisher.resource_manage import to_jsonfile
from config0_publisher.serialization import b64_encode

terraform_state_file = os.environ.get("TERRAFORM_STATE_FILE","terraform.tfstate")

with open(terraform_state_file) as json_file:
    data = json.load(json_file)

if not data:
    print("ERROR - there is no data from {}".format(os.path.join(os.getcwd(),terraform_state_file)))
    exit(9)

name = data["resources"][0]["instances"][0]["attributes"]["name"]

results = {"name":name}
results["name"] = name
results["resource_type"] = "ssh_public_key"
results["provider"] = "do"
results["main"] = True
results["_id"] = data["resources"][0]["instances"][0]["attributes"]["id"]
results["tags"] = [ results["_id"], name ]
#results["raw"] = {"terraform":data}

# ref 34532045732
to_jsonfile(results,"output.json")
